export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const FETCH_USER_LIST_REQUEST = 'FETCH_USER_LIST_REQUEST'
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS'
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR'

export const CREATE_USER_ITEM_REQUEST = 'CREATE_USER_ITEM_REQUEST'
export const CREATE_USER_ITEM_SUCCESS = 'CREATE_USER_ITEM_SUCCESS'
export const CREATE_USER_ITEM_ERROR = 'CREATE_USER_ITEM_ERROR'

export const DELETE_USER_ITEM_REQUEST = 'DELETE_USER_ITEM_REQUEST'
export const DELETE_USER_ITEM_SUCCESS = 'DELETE_USER_ITEM_SUCCESS'
export const DELETE_USER_ITEM_ERROR = 'DELETE_USER_ITEM_ERROR'
